# Generated by Django 4.1.3 on 2022-12-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_created_at_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='highest_bid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
