# Generated by Django 4.1.3 on 2022-12-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listing',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='starting_bid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
