# Generated by Django 4.1.3 on 2022-12-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_watchlist_listing_watchlist_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
