# Generated by Django 4.1.3 on 2022-12-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionlistings_slug_watchlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='highest_bid',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField()),
        ),
    ]
