# Generated by Django 4.1.3 on 2022-12-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionlistings_highest_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='highest_bid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
