# Generated by Django 4.1.3 on 2022-12-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_auctionlistings_auction_close_closedlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='session_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
