# Generated by Django 4.1.3 on 2022-12-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_comment_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='highest_bidder',
            name='listing_code',
            field=models.SlugField(default=''),
        ),
    ]
